// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFoy1UiX1RtzOPwOa9rMCiN9Zhq8vE2JA',
    appId: '1:800512881445:web:0c788b8f68b49cdd04e0cc',
    messagingSenderId: '800512881445',
    projectId: 'mynotes-kevin-app',
    authDomain: 'mynotes-kevin-app.firebaseapp.com',
    storageBucket: 'mynotes-kevin-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhLJG4fLHQoDiDFBngJ6xZ1ONQjpKbZFA',
    appId: '1:800512881445:android:b3aacd301f841e6504e0cc',
    messagingSenderId: '800512881445',
    projectId: 'mynotes-kevin-app',
    storageBucket: 'mynotes-kevin-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDrjS7ISYqOBVMfaVQygGHqK533dyBOFA',
    appId: '1:800512881445:ios:45aaa8b15f8c8bee04e0cc',
    messagingSenderId: '800512881445',
    projectId: 'mynotes-kevin-app',
    storageBucket: 'mynotes-kevin-app.appspot.com',
    iosBundleId: 'com.learnsomething.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDrjS7ISYqOBVMfaVQygGHqK533dyBOFA',
    appId: '1:800512881445:ios:45aaa8b15f8c8bee04e0cc',
    messagingSenderId: '800512881445',
    projectId: 'mynotes-kevin-app',
    storageBucket: 'mynotes-kevin-app.appspot.com',
    iosBundleId: 'com.learnsomething.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFoy1UiX1RtzOPwOa9rMCiN9Zhq8vE2JA',
    appId: '1:800512881445:web:89e51ec697a324c404e0cc',
    messagingSenderId: '800512881445',
    projectId: 'mynotes-kevin-app',
    authDomain: 'mynotes-kevin-app.firebaseapp.com',
    storageBucket: 'mynotes-kevin-app.appspot.com',
  );
}
